"""POST /rti/{id}: template RTI draft, addressed per state board, records for the flagged periods, no addresses."""

import json
import re

import pytest

from conftest import CLUSTER_IDS, EXPORT, call
from handlers import rti

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def detail(cid):
    return json.loads((EXPORT / f"cluster_{cid}.json").read_text(encoding="utf-8"))


def human(iso):
    y, m, d = iso.split("-")
    return f"{int(d)} {MONTHS[int(m) - 1]} {y}"


@pytest.mark.parametrize("cid", CLUSTER_IDS)
def test_rti_draft(cid):
    status, r = call("POST", "/rti/{id}", cid)
    assert status == 200 and set(r) == {"markdown", "plain_text"}
    c = detail(cid)
    md, txt = r["markdown"], r["plain_text"]
    operating = [p for p in c["plants"] if p["status"] == "operating"]
    states = sorted({p["state"] for p in operating})
    for text in (md, txt):
        assert "Section 6(1) of the Right to Information Act, 2005" in text
        assert text.count("The Public Information Officer,") == len(states)
        for s in states:
            assert rti.BOARDS[s] in text
        assert text.count("Verify the PIO address on the board's official website") == len(states)
        assert "satellite-based analysis indicates an anomaly warranting review" in text
        last = text.strip().splitlines()[-1]
        assert "Draft generated by PanoptiCoal. Not legal advice." in last and human(c["as_of"]) in last
        for p in operating:
            assert p["name"] in text
        for p in c["flagged_periods"]:
            assert f"{human(p['start'])} to {human(p['end'])}" in text
        for item in ("Inspection reports and monitoring reports", "Online Continuous Emission Monitoring System (OCEMS)",
                     "calibration", "data-availability", "Consent to Operate", "compliance reports",
                     "flue-gas desulphurisation (FGD)", "selective catalytic reduction (SCR)"):
            assert item in text
        for ph in ("[Applicant's full name]", "[Applicant's postal address]", "Rs 10", "Below Poverty Line", "BPL certificate",
                   "[Address of the Public Information Officer]"):
            assert ph in text
        assert f"{c['risk_score']:.0f}/100" in text
    assert "**" not in txt and not re.search(r"^#", txt, re.M)
    assert md.startswith(f"# Draft RTI application: {c['name']} cluster")


def test_multi_state_cluster_gets_one_application_per_board():
    md = call("POST", "/rti/{id}", "singrauli")[1]["markdown"]
    assert "Madhya Pradesh and Uttar Pradesh" in md and "file each one separately" in md
    mp, up = md.split("## Application to the Uttar Pradesh Pollution Control Board")
    assert "Vindhyachal STPS" in mp and "Vindhyachal STPS" not in up
    assert "Anpara TPS" in up and "Anpara TPS" not in mp


@pytest.mark.parametrize("cid", CLUSTER_IDS)
def test_no_invented_addresses_or_accusations(cid):
    txt = call("POST", "/rti/{id}", cid)[1]["plain_text"]
    # No PIN codes, phone numbers, emails or web addresses: the applicant fills them in or checks the board's site.
    assert not re.search(r"\b\d{6}\b", txt)
    assert not re.search(r"\b\d{3,5}[- ]\d{6,8}\b", txt)
    assert "@" not in txt and "http" not in txt and "www." not in txt and ".gov" not in txt and ".nic.in" not in txt
    low = txt.lower()
    for word in ("violated", "illegal", "guilty", "fraud", "falsif", "cheat", "culprit", "polluter"):
        assert word not in low
    assert "not evidence of any violation" in low and "not legal advice" in low


@pytest.mark.parametrize("cid", CLUSTER_IDS)
def test_numbers_come_from_the_export(cid):
    """Every number in the context paragraph is the score, a flagged-period peak, a date or the as-of date."""
    c = detail(cid)
    txt = call("POST", "/rti/{id}", cid)[1]["plain_text"]
    context = next(line for line in txt.splitlines() if line.startswith("Context."))
    allowed = {f"{c['risk_score']:.0f}", "100", "90", "5", "2", "6"}  # score, /100, 90-day, Sentinel-5P, NO2
    allowed |= {f"{p['peak_z']:.1f}" for p in c["flagged_periods"]}
    allowed |= set(re.findall(r"\d+", human(c["as_of"])))
    found = set(re.findall(r"\d+(?:\.\d+)?", context))
    assert found <= allowed, found - allowed


def test_score_window_fallback(aws):
    c = detail("korba")
    c["flagged_periods"] = [{"start": "2026-04-16", "end": "2026-07-14", "peak_z": 0.24, "reason": "score_window"}]
    aws.put_object(Bucket="panopticoal-test-data", Key="data/cluster_korba.json", Body=json.dumps(c).encode())
    txt = call("POST", "/rti/{id}", "korba")[1]["plain_text"]
    assert "latest 90-day window the score is based on" in txt and "16 Apr 2026 to 14 Jul 2026" in txt
    assert "standard deviations" not in txt


def test_unknown_state_board_is_generic():
    assert rti.board_for("Jharkhand") == "State Pollution Control Board, Jharkhand"
