// Intro paths: fresh load plays, ?intro=0 skips, footer "Replay intro" replays from another page,
// Skip button ends it early, reduced motion fades. Needs preview on 4173.
import { chromium } from 'playwright'
const b = await chromium.launch({ channel: 'chrome', args: ['--enable-gpu', '--ignore-gpu-blocklist'] })
const has = (p) => p.evaluate(() => !!document.querySelector('.intro'))
const nav = (p) => p.evaluate(() => document.documentElement.classList.contains('intro-hold'))
let p = await b.newPage({ viewport: { width: 1440, height: 900 } })
p.on('pageerror', (e) => console.log('[pageerror]', e.message))
await p.goto('http://localhost:4173/', { waitUntil: 'commit' })
await p.waitForTimeout(600)
console.log('fresh load: intro', await has(p), 'nav held', await nav(p))
await p.waitForTimeout(5500)
console.log('after ~6 s: intro', await has(p), 'nav held', await nav(p), 'hero in', await p.evaluate(() => !!document.querySelector('.hero.in')))
await p.goto('http://localhost:4173/?intro=0', { waitUntil: 'networkidle' })
console.log('?intro=0: intro', await has(p))
await p.goto('http://localhost:4173/limits', { waitUntil: 'networkidle' })
await p.click('.footer .linklike')
await p.waitForTimeout(500)
console.log('replay from /limits:', p.url(), 'intro', await has(p))
await p.waitForTimeout(1500)
await p.click('.intro-skip')
await p.waitForTimeout(1600)
console.log('after Skip (1.6 s): intro', await has(p), 'hero in', await p.evaluate(() => !!document.querySelector('.hero.in')))
await p.close()
p = await b.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' })
await p.goto('http://localhost:4173/', { waitUntil: 'commit' })
await p.waitForTimeout(900)
console.log('reduced motion after 0.9 s: intro', await has(p), 'hero in', await p.evaluate(() => !!document.querySelector('.hero.in')))
await b.close()
