// Checks the Home story chips: click, keyboard arrows, prev/next. Needs `npm run preview` on 4173.
import { chromium } from 'playwright'
const b = await chromium.launch({ channel: 'chrome', args: ['--enable-gpu', '--ignore-gpu-blocklist'] })
const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
p.on('pageerror', (e) => console.log('[pageerror]', e.message))
await p.goto('http://localhost:4173/?intro=0', { waitUntil: 'networkidle' })
await p.waitForTimeout(4500)
await p.mouse.wheel(0, 900)
await p.waitForTimeout(1500)
const active = () => p.evaluate(() => document.querySelector('.story-chip[aria-current="step"]')?.textContent)
console.log('after wheel:', await active())
await p.click('.story-chip >> nth=2')
await p.waitForTimeout(1700)
console.log('click 03:', await active(), 'y', await p.evaluate(() => scrollY))
await p.screenshot({ path: process.argv[2] })
await p.keyboard.press('ArrowRight')
await p.waitForTimeout(1700)
console.log('ArrowRight:', await active(), 'focus', await p.evaluate(() => document.activeElement?.textContent))
await p.click('.story-arrow[aria-label="Previous step"]')
await p.waitForTimeout(1700)
console.log('prev:', await active())
await p.click('.story-chip >> nth=0')
await p.waitForTimeout(1700)
console.log('click 01:', await active())
await b.close()
