"""POST /rti/{id}: a draft Right to Information application for a cluster's plants. Template only, no LLM.

One application per state the cluster's operating plants are in (each State Pollution Control Board is its
own public authority), addressed to its Public Information Officer. Addresses are never filled in: the
applicant is told to verify the PIO address on the board's official website. Requests records under
Section 6(1) of the RTI Act, 2005 for the flagged periods in cluster_{id}.json (risk_score.flagged_periods):
inspection/monitoring reports, OCEMS calibration and data-availability records, consent-to-operate
conditions and compliance reports, and FGD/SCR status and operation records. The context paragraph uses
only exported numbers and says the analysis indicates an anomaly warranting review, not a violation.

Returns {"markdown": str, "plain_text": str}: the same draft, rendered twice from one block list.
"""

from handlers import data

FOOTER = "Draft generated by PanoptiCoal. Not legal advice."
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# Board names only (no addresses). States not listed fall back to a generic description.
BOARDS = {
    "Bihar": "Bihar State Pollution Control Board",
    "Chhattisgarh": "Chhattisgarh Environment Conservation Board",
    "Gujarat": "Gujarat Pollution Control Board",
    "Madhya Pradesh": "Madhya Pradesh Pollution Control Board",
    "Maharashtra": "Maharashtra Pollution Control Board",
    "Odisha": "State Pollution Control Board, Odisha",
    "Tamil Nadu": "Tamil Nadu Pollution Control Board",
    "Telangana": "Telangana State Pollution Control Board",
    "Uttar Pradesh": "Uttar Pradesh Pollution Control Board",
}
LEVEL = {"high": "high", "medium": "medium", "low": "low"}


def board_for(state: str) -> str:
    return BOARDS.get(state, f"State Pollution Control Board, {state}")


def _date(iso: str) -> str:
    y, m, d = iso.split("-")
    return f"{int(d)} {MONTHS[int(m) - 1]} {y}"


def _render(blocks: list[tuple[str, str]]) -> tuple[str, str]:
    """blocks: (kind, text) with kind in h1, h2, p, line, bullet, num, note, rule, small."""
    md, txt = [], []
    n = 0
    for kind, text in blocks:
        if kind != "num":
            n = 0
        if kind == "h1":
            md += [f"# {text}", ""]
            txt += [text.upper(), ""]
        elif kind == "h2":
            md += [f"## {text}", ""]
            txt += [text, "-" * len(text), ""]
        elif kind == "p":
            md += [text, ""]
            txt += [text, ""]
        elif kind == "line":  # address-style lines kept together
            md += [text + "  "]
            txt += [text]
        elif kind == "gap":
            md += [""]
            txt += [""]
        elif kind == "bullet":
            md += [f"- {text}"]
            txt += [f"- {text}"]
        elif kind == "num":
            n += 1
            md += [f"{n}. {text}"]
            txt += [f"{n}. {text}"]
        elif kind == "note":
            md += [f"> {text}", ""]
            txt += [f"NOTE: {text}", ""]
        elif kind == "rule":
            md += ["---", ""]
            txt += ["-" * 60, ""]
        elif kind == "small":
            md += [f"_{text}_", ""]
            txt += [text, ""]
    return "\n".join(md).rstrip() + "\n", "\n".join(txt).rstrip() + "\n"


def _application(c: dict, state: str, plants: list[dict], periods: list[dict], multi: bool) -> list[tuple[str, str]]:
    board = board_for(state)
    names = ", ".join(p["name"] for p in plants)
    excess = [p for p in periods if p.get("reason") == "excess"]
    score_only = not excess
    b: list[tuple[str, str]] = []
    if multi:
        b.append(("h2", f"Application to the {board}"))
    b += [
        ("line", "To,"),
        ("line", "The Public Information Officer,"),
        ("line", f"{board}"),
        ("line", "[Address of the Public Information Officer]"),
        ("gap", ""),
        ("note", "Verify the PIO address on the board's official website before sending. PanoptiCoal does not "
                 "supply addresses."),
        ("line", "From,"),
        ("line", "[Applicant's full name]"),
        ("line", "[Applicant's postal address]"),
        ("line", "[Phone / email (optional)]"),
        ("gap", ""),
        ("line", "Date: [DD/MM/YYYY]"),
        ("gap", ""),
        ("p", f"**Subject:** Request for information under Section 6(1) of the Right to Information Act, 2005: "
              f"pollution-control records of {names} ({c['name']} cluster, {state})"),
        ("p", "Sir/Madam,"),
        ("p", "I am a citizen of India. Under Section 6(1) of the Right to Information Act, 2005, I request copies "
              "of the records listed below, held by or under the control of the Board."),
    ]
    # Neutral context: exported numbers only.
    peak = max((p["peak_z"] for p in excess), default=None)
    context = (f"**Context.** PanoptiCoal, an independent screening tool, compares Sentinel-5P satellite NO2 around "
               f"the {c['name']} cluster with the generation its plants report to the Central Electricity Authority, "
               f"adjusted for wind, boundary-layer height and season. This satellite-based analysis indicates an "
               f"anomaly warranting review: as of {_date(c['as_of'])} the cluster's Audit Risk Score is "
               f"{c['risk_score']:.0f}/100 ({LEVEL.get(c['risk_level'], c['risk_level'])} risk, "
               f"{LEVEL.get(c['confidence'], c['confidence'])} confidence). ")
    if score_only:
        context += "The period below is the latest 90-day window the score is based on. "
    else:
        context += (f"In the periods below, the 90-day mean NO2 around the cluster was higher than reported generation "
                    f"and weather predict, up to {peak:.1f} standard deviations above the cluster's own history. ")
    context += ("Satellite NO2 is a column average over several kilometres, not a measurement of any plant's "
                "emissions, and other sources also emit NO2. It is not evidence of any violation. I am requesting "
                "the records so that the satellite signal can be compared with the Board's own monitoring.")
    b.append(("p", context))

    b.append(("p", "**Plants** (operating, as listed in PanoptiCoal's registry):"))
    b += [("bullet", f"{p['name']} ({p['capacity_mw']:,.0f} MW)") for p in plants]
    b.append(("gap", ""))
    b.append(("p", "**Periods:**"))
    b += [("bullet", f"{_date(p['start'])} to {_date(p['end'])}") for p in periods]
    b.append(("gap", ""))

    b.append(("p", "**Records requested** for each plant above, for each period above:"))
    b += [
        ("num", "Inspection reports and monitoring reports (stack emission and ambient air quality sampling, including "
                "analysis results) prepared or received by the Board for the plants."),
        ("num", "Online Continuous Emission Monitoring System (OCEMS) records: calibration and validation records of "
                "the analysers, and data-availability, downtime and data-gap reports for the plants' OCEMS feeds to "
                "the Board."),
        ("num", "The Consent to Operate in force for each plant, with all its conditions, and the compliance reports "
                "the plants submitted against those conditions."),
        ("num", "Records of the status and operation of emission-control equipment, including flue-gas "
                "desulphurisation (FGD) and selective catalytic reduction (SCR) or other NOx controls: installation or "
                "commissioning status, operating and bypass records, and any directions the Board issued concerning them."),
        ("gap", ""),
        ("p", "If any of this information is held by another public authority, please transfer the relevant part of "
              "this application under Section 6(3) of the Act. I would prefer the information in electronic form "
              "(PDF by email); otherwise please send photocopies to the address above."),
        ("p", "**Fee:** [I have paid the application fee of Rs 10 by (Indian Postal Order / demand draft / court-fee "
              "stamp / online payment), reference (number), dated (date).] OR [I belong to the Below Poverty Line "
              "category; a copy of my BPL certificate is enclosed, so no fee is payable.]"),
        ("note", f"Verify the application fee and accepted payment modes under the RTI rules that apply to the "
                 f"{board} before sending."),
        ("line", "Yours faithfully,"),
        ("gap", ""),
        ("line", "[Signature]"),
        ("line", "[Applicant's full name]"),
        ("line", "Place: [Place]"),
        ("gap", ""),
        ("p", "**Enclosures:** [Proof of fee payment, or copy of BPL certificate]"),
    ]
    return b


def make_rti(cid: str) -> dict:
    data.require_cluster(cid)
    c = data.get_json(f"cluster_{cid}.json")
    operating = [p for p in c.get("plants", []) if p.get("status") == "operating"]
    states = sorted({p["state"] for p in operating})
    periods = c.get("flagged_periods") or []
    blocks: list[tuple[str, str]] = [("h1", f"Draft RTI application: {c['name']} cluster")]
    if len(states) > 1:
        blocks.append(("note", f"The {c['name']} cluster has plants in {' and '.join(states)}. Each State Pollution "
                               f"Control Board is a separate public authority, so this draft has one application per "
                               f"board; file each one separately."))
    for i, state in enumerate(states):
        if i:
            blocks.append(("rule", ""))
        blocks += _application(c, state, [p for p in operating if p["state"] == state], periods, len(states) > 1)
    blocks += [("rule", ""), ("small", f"{FOOTER} Numbers from the PanoptiCoal data as of {_date(c['as_of'])}.")]
    markdown, plain_text = _render(blocks)
    return {"markdown": markdown, "plain_text": plain_text.replace("**", "")}
